'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LGMD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AppTitle.
        '''</summary>
        Friend ReadOnly Property AppTitle() As String
            Get
                Return ResourceManager.GetString("AppTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackingUp.
        '''</summary>
        Friend ReadOnly Property BackingUp() As String
            Get
                Return ResourceManager.GetString("BackingUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackupComplete.
        '''</summary>
        Friend ReadOnly Property BackupComplete() As String
            Get
                Return ResourceManager.GetString("BackupComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property black1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Columns.
        '''</summary>
        Friend ReadOnly Property Columns() As String
            Get
                Return ResourceManager.GetString("Columns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CompletedPercent.
        '''</summary>
        Friend ReadOnly Property CompletedPercent() As String
            Get
                Return ResourceManager.GetString("CompletedPercent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DatabaseDeleted.
        '''</summary>
        Friend ReadOnly Property DatabaseDeleted() As String
            Get
                Return ResourceManager.GetString("DatabaseDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Databases.
        '''</summary>
        Friend ReadOnly Property Databases() As String
            Get
                Return ResourceManager.GetString("Databases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DataType.
        '''</summary>
        Friend ReadOnly Property DataType() As String
            Get
                Return ResourceManager.GetString("DataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DateCreated.
        '''</summary>
        Friend ReadOnly Property DateCreated() As String
            Get
                Return ResourceManager.GetString("DateCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DummyNode.
        '''</summary>
        Friend ReadOnly Property DummyNode() As String
            Get
                Return ResourceManager.GetString("DummyNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DuplicateDatabaseName.
        '''</summary>
        Friend ReadOnly Property DuplicateDatabaseName() As String
            Get
                Return ResourceManager.GetString("DuplicateDatabaseName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GeneratedScript.
        '''</summary>
        Friend ReadOnly Property GeneratedScript() As String
            Get
                Return ResourceManager.GetString("GeneratedScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property internetconnection() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("internetconnection", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jicaLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jicaLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jicaLogoo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jicaLogoo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jicaLogoo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jicaLogoo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property library() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("library", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logOffIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logOffIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NoDatabaseName.
        '''</summary>
        Friend ReadOnly Property NoDatabaseName() As String
            Get
                Return ResourceManager.GetString("NoDatabaseName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NoSqlServers.
        '''</summary>
        Friend ReadOnly Property NoSqlServers() As String
            Get
                Return ResourceManager.GetString("NoSqlServers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ObjectName.
        '''</summary>
        Friend ReadOnly Property ObjectName() As String
            Get
                Return ResourceManager.GetString("ObjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property oEdit21() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("oEdit21", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ProgressCharacter.
        '''</summary>
        Friend ReadOnly Property ProgressCharacter() As String
            Get
                Return ResourceManager.GetString("ProgressCharacter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PropertyName.
        '''</summary>
        Friend ReadOnly Property PropertyName() As String
            Get
                Return ResourceManager.GetString("PropertyName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you really want to drop ?.
        '''</summary>
        Friend ReadOnly Property ReallyDrop() As String
            Get
                Return ResourceManager.GetString("ReallyDrop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you really want to restore?.
        '''</summary>
        Friend ReadOnly Property ReallyRestore() As String
            Get
                Return ResourceManager.GetString("ReallyRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Reports() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Reports", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RestoreComplete.
        '''</summary>
        Friend ReadOnly Property RestoreComplete() As String
            Get
                Return ResourceManager.GetString("RestoreComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring.
        '''</summary>
        Friend ReadOnly Property Restoring() As String
            Get
                Return ResourceManager.GetString("Restoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server.
        '''</summary>
        Friend ReadOnly Property Server() As String
            Get
                Return ResourceManager.GetString("Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServerMessage.
        '''</summary>
        Friend ReadOnly Property ServerMessage() As String
            Get
                Return ResourceManager.GetString("ServerMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ShortcutIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ShortcutIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SqlError.
        '''</summary>
        Friend ReadOnly Property SqlError() As String
            Get
                Return ResourceManager.GetString("SqlError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SqlInfoMessage.
        '''</summary>
        Friend ReadOnly Property SqlInfoMessage() As String
            Get
                Return ResourceManager.GetString("SqlInfoMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SqlStatementExecuted.
        '''</summary>
        Friend ReadOnly Property SqlStatementExecuted() As String
            Get
                Return ResourceManager.GetString("SqlStatementExecuted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StateChanged.
        '''</summary>
        Friend ReadOnly Property StateChanged() As String
            Get
                Return ResourceManager.GetString("StateChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Status_Open() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Status_Open", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Thumbs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Thumbs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ToolWorkOffline() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolWorkOffline", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnOffButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnOffButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TZLogo_small1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TZLogo small1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UnrecognizedType.
        '''</summary>
        Friend ReadOnly Property UnrecognizedType() As String
            Get
                Return ResourceManager.GetString("UnrecognizedType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urn.
        '''</summary>
        Friend ReadOnly Property Urn() As String
            Get
                Return ResourceManager.GetString("Urn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UsedBy.
        '''</summary>
        Friend ReadOnly Property UsedBy() As String
            Get
                Return ResourceManager.GetString("UsedBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property user() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property users() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("users", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend ReadOnly Property Value() As String
            Get
                Return ResourceManager.GetString("Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yellow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yellow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
