
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("06d47ce7-161f-4bbf-8e81-7f4abd5cfb93")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("LGMD2iModel", "FK_LivestockService01_LivestockList", "LivestockList", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(LivestockList), "LivestockService01", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(LivestockService01))>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class LGMD2iEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new LGMD2iEntities object using the connection string found in the 'LGMD2iEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=LGMD2iEntities", "LGMD2iEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new LGMD2iEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "LGMD2iEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new LGMD2iEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "LGMD2iEntities")
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property LivestockList() As ObjectSet(Of LivestockList)
        Get
            If (_LivestockList Is Nothing) Then
                _LivestockList = MyBase.CreateObjectSet(Of LivestockList)("LivestockList")
            End If
            Return _LivestockList
        End Get
    End Property

    Private _LivestockList As ObjectSet(Of LivestockList)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property LivestockService01() As ObjectSet(Of LivestockService01)
        Get
            If (_LivestockService01 Is Nothing) Then
                _LivestockService01 = MyBase.CreateObjectSet(Of LivestockService01)("LivestockService01")
            End If
            Return _LivestockService01
        End Get
    End Property

    Private _LivestockService01 As ObjectSet(Of LivestockService01)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the LivestockList EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLivestockList(ByVal livestockList As LivestockList)
        MyBase.AddObject("LivestockList", livestockList)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the LivestockService01 EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLivestockService01(ByVal livestockService01 As LivestockService01)
        MyBase.AddObject("LivestockService01", livestockService01)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="LGMD2iModel", Name:="LivestockList")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class LivestockList
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new LivestockList object.
    ''' </summary>
    ''' <param name="livestockListID">Initial value of the LivestockListID property.</param>
    Public Shared Function CreateLivestockList(livestockListID As Global.System.Int32) As LivestockList
        Dim livestockList as LivestockList = New LivestockList
        livestockList.LivestockListID = livestockListID
        Return livestockList
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LivestockListID() As Global.System.Int32
        Get
            Return _LivestockListID
        End Get
        Set
            If (_LivestockListID <> Value) Then
                OnLivestockListIDChanging(value)
                ReportPropertyChanging("LivestockListID")
                _LivestockListID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("LivestockListID")
                OnLivestockListIDChanged()
            End If
        End Set
    End Property

    Private _LivestockListID As Global.System.Int32
    Private Partial Sub OnLivestockListIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnLivestockListIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LivestockName() As Global.System.String
        Get
            Return _LivestockName
        End Get
        Set
            OnLivestockNameChanging(value)
            ReportPropertyChanging("LivestockName")
            _LivestockName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LivestockName")
            OnLivestockNameChanged()
        End Set
    End Property

    Private _LivestockName As Global.System.String
    Private Partial Sub OnLivestockNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLivestockNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("LGMD2iModel", "FK_LivestockService01_LivestockList", "LivestockService01")>
     Public Property LivestockService01() As EntityCollection(Of LivestockService01)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of LivestockService01)("LGMD2iModel.FK_LivestockService01_LivestockList", "LivestockService01")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of LivestockService01)("LGMD2iModel.FK_LivestockService01_LivestockList", "LivestockService01", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="LGMD2iModel", Name:="LivestockService01")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class LivestockService01
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new LivestockService01 object.
    ''' </summary>
    ''' <param name="livestockServiceID">Initial value of the LivestockServiceID property.</param>
    Public Shared Function CreateLivestockService01(livestockServiceID As Global.System.Guid) As LivestockService01
        Dim livestockService01 as LivestockService01 = New LivestockService01
        livestockService01.LivestockServiceID = livestockServiceID
        Return livestockService01
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LivestockServiceID() As Global.System.Guid
        Get
            Return _LivestockServiceID
        End Get
        Set
            If (_LivestockServiceID <> Value) Then
                OnLivestockServiceIDChanging(value)
                ReportPropertyChanging("LivestockServiceID")
                _LivestockServiceID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("LivestockServiceID")
                OnLivestockServiceIDChanged()
            End If
        End Set
    End Property

    Private _LivestockServiceID As Global.System.Guid
    Private Partial Sub OnLivestockServiceIDChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnLivestockServiceIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CuttingHoof() As Nullable(Of Global.System.Int32)
        Get
            Return _CuttingHoof
        End Get
        Set
            OnCuttingHoofChanging(value)
            ReportPropertyChanging("CuttingHoof")
            _CuttingHoof = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CuttingHoof")
            OnCuttingHoofChanged()
        End Set
    End Property

    Private _CuttingHoof As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCuttingHoofChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCuttingHoofChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Castration() As Nullable(Of Global.System.Int32)
        Get
            Return _Castration
        End Get
        Set
            OnCastrationChanging(value)
            ReportPropertyChanging("Castration")
            _Castration = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Castration")
            OnCastrationChanged()
        End Set
    End Property

    Private _Castration As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCastrationChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCastrationChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property AI() As Nullable(Of Global.System.Int32)
        Get
            Return _AI
        End Get
        Set
            OnAIChanging(value)
            ReportPropertyChanging("AI")
            _AI = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AI")
            OnAIChanged()
        End Set
    End Property

    Private _AI As Nullable(Of Global.System.Int32)
    Private Partial Sub OnAIChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnAIChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CuttingHorn() As Nullable(Of Global.System.Int32)
        Get
            Return _CuttingHorn
        End Get
        Set
            OnCuttingHornChanging(value)
            ReportPropertyChanging("CuttingHorn")
            _CuttingHorn = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CuttingHorn")
            OnCuttingHornChanged()
        End Set
    End Property

    Private _CuttingHorn As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCuttingHornChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCuttingHornChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Branding() As Nullable(Of Global.System.Int32)
        Get
            Return _Branding
        End Get
        Set
            OnBrandingChanging(value)
            ReportPropertyChanging("Branding")
            _Branding = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Branding")
            OnBrandingChanged()
        End Set
    End Property

    Private _Branding As Nullable(Of Global.System.Int32)
    Private Partial Sub OnBrandingChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnBrandingChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CuttingTail() As Nullable(Of Global.System.Int32)
        Get
            Return _CuttingTail
        End Get
        Set
            OnCuttingTailChanging(value)
            ReportPropertyChanging("CuttingTail")
            _CuttingTail = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CuttingTail")
            OnCuttingTailChanged()
        End Set
    End Property

    Private _CuttingTail As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCuttingTailChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCuttingTailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CuttingTeeth() As Nullable(Of Global.System.Int32)
        Get
            Return _CuttingTeeth
        End Get
        Set
            OnCuttingTeethChanging(value)
            ReportPropertyChanging("CuttingTeeth")
            _CuttingTeeth = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CuttingTeeth")
            OnCuttingTeethChanged()
        End Set
    End Property

    Private _CuttingTeeth As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCuttingTeethChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCuttingTeethChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CuttingBillBeak() As Nullable(Of Global.System.Int32)
        Get
            Return _CuttingBillBeak
        End Get
        Set
            OnCuttingBillBeakChanging(value)
            ReportPropertyChanging("CuttingBillBeak")
            _CuttingBillBeak = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CuttingBillBeak")
            OnCuttingBillBeakChanged()
        End Set
    End Property

    Private _CuttingBillBeak As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCuttingBillBeakChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCuttingBillBeakChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MonthlyRecordID() As Nullable(Of Global.System.Guid)
        Get
            Return _MonthlyRecordID
        End Get
        Set
            OnMonthlyRecordIDChanging(value)
            ReportPropertyChanging("MonthlyRecordID")
            _MonthlyRecordID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MonthlyRecordID")
            OnMonthlyRecordIDChanged()
        End Set
    End Property

    Private _MonthlyRecordID As Nullable(Of Global.System.Guid)
    Private Partial Sub OnMonthlyRecordIDChanging(value As Nullable(Of Global.System.Guid))
    End Sub

    Private Partial Sub OnMonthlyRecordIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("LGMD2iModel", "FK_LivestockService01_LivestockList", "LivestockList")>
    Public Property LivestockList() As LivestockList
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of LivestockList)("LGMD2iModel.FK_LivestockService01_LivestockList", "LivestockList").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of LivestockList)("LGMD2iModel.FK_LivestockService01_LivestockList", "LivestockList").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property LivestockListReference() As EntityReference(Of LivestockList)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of LivestockList)("LGMD2iModel.FK_LivestockService01_LivestockList", "LivestockList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of LivestockList)("LGMD2iModel.FK_LivestockService01_LivestockList", "LivestockList", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


